kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-cos # Enter the name of the PVC.
  namespace: db2-test-6 # Enter the namespace where you want to create the PVC. The PVC must be created in the same namespace where you created the Kubernetes secret for your service credentials and where you want to run your pod.
  annotations:
    ibm.io/auto-create-bucket: "true"
    ibm.io/auto-delete-bucket: "true"
    ibm.io/quota-limit: "true" 
    ibm.io/endpoint: "https://s3.us-east.cloud-object-storage.appdomain.cloud"
    ibm.io/tls-cipher-suite: "default"
    ibm.io/secret-name: "cos-write-access" 
    ibm.io/secret-namespace: "db2-test-6" #ten cuidado, revisa donde guardaste el secret con las credenciales hmac.
    ibm.io/add-mount-param: "nonempty" # s3fs mount options
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # Enter the size of the PVC.
  storageClassName: ibmc-s3fs-standard-regional